### ISSUE TITLE
Error: command "docker service ls | awk '{print $2}' | egrep "^root_lb$"" failed:

### ISSUE THREAD

**Issue by petergombos** [ddrozdov/docker-compose-swarm-mode#23]
I'm getting this error when trying to docker-compose-swarm-mode up this conf:

```
version: '2'
services:
  lb:
    image: dockercloud/haproxy:staging
    links:
      - api_v1
      - api_v2
      - salespage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
  api_v1:
    image: barflow/api:latest
    ports:
    - "3000"
    depends_on:
    - mongo
    environment:
      - DB=$DB
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=$NODE_ENV
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - VIRTUAL_HOST=api.barflow.io/v1/*
  api_v2:
    image: barflow/api:v2
    ports:
    - "3000"
    depends_on:
    - mongo
    environment:
      - DB=$DB
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=$NODE_ENV
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - VIRTUAL_HOST=api.barflow.io/v2/*
  salespage:
    image: barflow/salespage
    ports:
    - "8080"
    environment:
      - VIRTUAL_HOST=barflow.io
  mongo:
    image: mongo:3.2
    ports:
    - "27017"
    volumes:
    - ./data:/data/db

```
