### ISSUE TITLE
problem starting a service

### ISSUE THREAD

**Issue by chromerobv** [ddrozdov/docker-compose-swarm-mode#30]
so whenever i try and start a service i get this.Running:
# docker-compose-swarm-mode -f ./allocation.test.yml  start

docker service scale compose_allocation.test=1

Error: command "docker service scale compose_allocation.test=1" failed: compose_allocation.test: Error: No such service: compose_allocation.test

here is my compose file.

version: "2"
services:
    allocation.test:
       ports:
          - "8080"

```
   environment:
      - affinity:mytag!=~allocation.test-1477688386
      - crSpringServer=allocation
      - SPRING_CONFIG_NAME=allocation
      - SPRING_CONFIG_LOCATION=/opt/props/
      - SPRING_PROFILES_ACTIVE=dev
      - CR_PROPERTIES_FILES_LOCATION=/opt/props
      - crEnv=dev
      - JAVAAGENT=-Xms256m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/props/allocation-test.hprof -Dnewrelic.environment=allocation -Dnewrelic.config.file=/opt/newrelic/newrelic-dev.yml -javaagent:/opt/newrelic/newrelic.jar

   labels:
      - "interlock.hostname=allocation"
      - "interlock.health_check=GET /health"
      - "interlock.health_check_interval=10000"
      - "interlock.domain=dev.pool.chromeriver.com"
      - "mytag=allocation.test-1477688386"
      - "crEnv=dev"
      - "cr_whoami=allocation.test"
      - "cr_started=1477688386"

   logging:
      driver: "gelf"
      options:
         gelf-address: "udp://localhost:12201"
         tag: "allocation.test"
   network_mode: default

   volumes:
      - /opt/chromeriver/props/common/dev:/opt/props
      - /opt/newrelic:/opt/newrelic

   mem_limit: 1536M
   restart: always
   image: mine/allocation:2.25.0-SNAPSHOT
```
