### ISSUE TITLE
Labels in dictionary outputted with missing values

### ISSUE THREAD

**Issue by kinghuang** [ddrozdov/docker-compose-swarm-mode#37]
[Docker Compose labels](https://docs.docker.com/compose/compose-file/#/labels) can be written using either an array or a dictionary. The default output format from `docker-compose config` uses dictionaries.

docker-compose-swarm-mode doesn't handle labels as dictionaries correctly. Only the dictionary keys are emitted for the generated `docker service create …` commands.

Example input compose service (excerpt):

```yaml
services:
  converis-web:
    image: docker.ucalgary.ca/tr/converis-web:1.1.0
    labels:
      - "ca.ucalgary.rms.stage=dev"
      - "traefik.frontend.rule=Host:master.rms-dev.ucalgary.ca"
      - "traefik.frontend.entryPoints=http"
      - "traefik.port=80"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net
```

Actual docker-compose-swarm-mode output:

```bash
Running: 
docker service create --with-registry-auth \
 --name rms_converis-web \
 --label ca.ucalgary.rms.stage \
 --label traefik.frontend.rule \
 --label traefik.frontend.entryPoints \
 --label traefik.port \
 --label traefik.docker.network \
 --network traefik-net \
 docker.ucalgary.ca/tr/converis-web:1.1.0
```

Expected docker-compose-swarm-mode output:

```bash
Running: 
docker service create --with-registry-auth \
 --name rms_converis-web \
 --label ca.ucalgary.rms.stage=dev \
 --label traefik.frontend.rule=Host:master.rms-dev.ucalgary.ca \
 --label traefik.frontend.entryPoints=http \
 --label traefik.port=80 \
 --label traefik.docker.network=traefik-net \
 --network traefik-net \
 docker.ucalgary.ca/tr/converis-web:1.1.0
```

Array form labels are outputted correctly.
